# added so that it does commit
image: codinget/webs1

stages:
 - build
 - test

build:
  stage: build
  script:
   - ./build/css.sh
   - ./build/template.lua
   - ./build/assets.sh
   - ./build/zip.sh
  artifacts:
    paths:
      - "out.zip"

test:
  stage: test
  script:
   - ./test/unpack.sh
   - ./test/htmlcheck.sh
